{{- if eq .Values.environment "dev" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.selfSigned.issuerName }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.selfSigned.certificateName }}
spec:
  secretName: {{ .Values.certManager.selfSigned.secretName }}
  duration: {{ .Values.certManager.selfSigned.duration }}
  renewBefore: {{ .Values.certManager.selfSigned.renewBefore }}
  dnsNames:
    - {{ include "app.domain" . | quote }}
  issuerRef:
    name: {{ .Values.certManager.selfSigned.issuerName }}
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
{{- else if eq .Values.environment "prod" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.letsEncrypt.issuerName }}
spec:
  acme:
    server: {{ .Values.certManager.letsEncrypt.server }}
    email: {{ .Values.certManager.letsEncrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className }}
{{- end }}
