{{/* templates/deployment.yaml */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment | quote }}
            - name: SECRET_TEXT
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SECRET_TEXT
          volumeMounts:
            - name: nginx-templates
              mountPath: /etc/nginx/templates/
            - name: nginx-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: nginx-templates
          configMap:
            name: nginx-config
            items:
              - key: 10-variables.conf.template
                path: 10-variables.conf.template
              - key: default.conf.template
                path: default.conf.template
        - name: nginx-html
          configMap:
            name: nginx-config
            items:
              - key: index.html
                path: index.html
