apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if eq .Values.environment "prod" }}
    cert-manager.io/cluster-issuer: {{ .Values.certManager.letsEncrypt.issuerName }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ include "app.domain" . }}
      {{- if eq .Values.environment "dev" }}
      secretName: {{ .Values.certManager.selfSigned.secretName }}
      {{- else if eq .Values.environment "prod" }}
      secretName: {{ include "app.domain" . }}-tls
      {{- end }}
  rules:
    - host: {{ include "app.domain" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.name }}
                port:
                  number: {{ .Values.service.port }}
